### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by stevemessick**
@jakemac53 @sigmundch 

Need to increment the version in order to publish the changes, right? I know I did this edit once before but it seems to have gotten lost.

### CODE REVIEW

**Comment by jakemac53** [comment]
Can you update the changelog as well, otherwise lgtm

**Comment by stevemessick** [comment]
Done. Do I need another LGTM or should I just merge it?

**Comment by jakemac53** [comment]
do you need one of us to publish or can you do that?

**Comment by jakemac53** [comment]
I also just added a tag `v0.3.6+2`

**Comment by stevemessick** [comment]
I'm trying to publish. It just keeps incrementing the timer. After 3
minutes I killed it and started over. It is up to 2m again and still going.
Is that normal?

**Comment by jakemac53** [comment]
no its not :(. I can try in a little bit.

**Comment by jakemac53** [comment]
You should be able to use the git tag though

**Comment by jakemac53** [comment]
Ok, published

**Comment by stevemessick** [comment]
What command did you use?

**Pull request merged**
